### ISSUE TITLE
Ansible crashes on editing the ini file

### ISSUE THREAD

**Issue by ehmo** [thefinn93/ansible-letsencrypt#15] opened 2016-03-10 22:39 UTC
Seems like the `ConfigParser` is expecting a clean .ini file but the file generated by letsencrypt starts with 4 lines of certificate and then there are values.

```
cert = /etc/letsencrypt/live/domain/cert.pem
privkey = /etc/letsencrypt/live/domain/privkey.pem
chain = /etc/letsencrypt/live/domain/chain.pem
fullchain = /etc/letsencrypt/live/domain/fullchain.pem

# Options and defaults used in the renewal process
[renewalparams]
no_self_upgrade = False
no_verify_ssl = False
ifaces = None
register_unsafely_without_email = False

```
The resulting error is `ConfigParser.MissingSectionHeaderError: File contains no section headers.` which makes sense, as there is no header section at the beginning.

Any idea why is this? I mean, I can "manually" add header section, but will it not tamper with the letsencrypt?

**Comment by thefinn93** [comment] 2016-03-10 22:53
Duplicate of #14. I'll go revert the renewal fixes for now, cuz I haven't had time to get it working

**Closed by thefinn93** 2016-03-10 22:53 UTC

**Comment by ehmo** [comment] 2016-03-10 23:11
Oh, sorry for the duplication.
